version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile-server
    ports:
      - 5555:5555
    networks:
      mynetwork:
        ipv4_address: 192.168.1.100
  
  client1:
    build:
      context: ./client
      dockerfile: Dockerfile-client
    depends_on:
      - server
    environment:
      - SERVER_HOST=server
      - SERVER_PORT=5555
    ports:
      - 5556:5556
    networks:
      mynetwork:
        ipv4_address: 192.168.1.101

  client2:
    build:
      context: ./client
      dockerfile: Dockerfile-client
    depends_on:
      - server
    environment:
      - SERVER_HOST=server
      - SERVER_PORT=5555
    ports:
      - 5557:5557
    networks:
      mynetwork:
        ipv4_address: 192.168.1.102

  client3:
    build:
      context: ./client
      dockerfile: Dockerfile-client
    depends_on:
      - server
    environment:
      - SERVER_HOST=server
      - SERVER_PORT=5555
    ports:
      - 5558:5558
    networks:
      mynetwork:
        ipv4_address: 192.168.1.103
  
  client4:
    build:
      context: ./client
      dockerfile: Dockerfile-client
    depends_on:
      - server
    environment:
      - SERVER_HOST=server
      - SERVER_PORT=5555
    ports:
      - 5559:5559
    networks:
      mynetwork:
        ipv4_address: 192.168.1.104

networks:
  mynetwork:
    ipam:
      config:
        - subnet: 192.168.1.0/16
